ISW_2018/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("booking.urls")),
]

booking/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "booking"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("login/<slug:loginErrato>", views.loginError, name="loginErrato"),
    path("home/", views.home, name="home"),
    path("logout/", views.logout, name="logout"),
    path("hotels/", views.manageHotel, name='hotels'),
    path("hoteldetail/<str:hotel>", views.manageCamera, name="hoteldetail"),
    path("#", views.search, name="search"),
    path("#c", views.prenota, name="prenota"),
    path("registrazione/#", views.registraUtente, name="registraUtente"),
    path("registrazione/", views.registrazione, name="registrazione"),
    path("errorpage", views.errorpage, name="errorpage"),
    path("errorpage/#", views.errorpageredirect, name="errorpageredirect")
]

booking/models.py
from typing import Any

from django.db import models
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User

# Create your models here.

class Hotel(models.Model):
    nome = models.CharField(max_length=100)
    descrizione = models.CharField(max_length=100)
    citta = models.CharField(max_length=100)
    indirizzo = models.CharField(max_length=100)
    proprietario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.nome



class Camera(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    numero = models.PositiveIntegerField()
    posti_letto = models.PositiveIntegerField()
    servizi = models.TextField()

    def __str__(self):
        return "Stanza " + str(self.numero) + " dell'Hotel " + str(self.hotel)

    class Meta:
        verbose_name_plural = "camere"


class Prenotazione(models.Model):
    email = models.EmailField(max_length=100)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    checkin = models.DateField()
    checkout = models.DateField()

    def __str__(self):
        return "Prenotazione di " + str(self.email) + " nella " + str(self.camera)

    class Meta:
        verbose_name_plural = "prenotazioni"

booking/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Camera

from .models import *


from django.contrib.auth.forms import UserCreationForm


class RegisterUserForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': "form-control", 'id':"exampleInputEmail1", 'aria-describedby':"emailHelp", 'placeholder':"Inserisci Email", 'name':"email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control", 'id':"exampleInputPassword1", 'placeholder':"Password", 'name':"password"}))
    confirmpassword = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control", 'id':"exampleInputPasswordConferma", 'placeholder':"Conferma Password"}))
    nome = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control", 'id':"nameUtente", 'placeholder': "Nome", 'name':"nome"}))
    cognome = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control", 'id':"cognomeUtente", 'placeholder': "Cognome", 'name':"cognome"}))

    class Meta:
        model = User
        fields = ("email", "password", "confirmpassword", "nome", "cognome")

    def save(self):
        user = User.objects.create_user(username=self.cleaned_data['email'], email=self.cleaned_data['email'], password=self.cleaned_data['password'])
        user.first_name = self.cleaned_data['nome']
        user.last_name = self.cleaned_data['cognome']
        user.save()
        return user


class AddHotelForm(forms.Form):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", 'id': "Nome", 'placeholder': "Nome", 'name': "nome"}))
    descrizione = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", 'id': "Descrizione", 'placeholder': "Descrizione", 'name': "descrizione"}))
    citta = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", 'id': "Citta", 'placeholder': "Citta", 'name': "citta"}))
    indirizzo = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", 'id': "Indirizzo", 'placeholder': "Indirizzo", 'name': "indirizzo"}))

    class Meta:
        model = Hotel
        fields = ("nome", "descrizione", "citta", "indirizzo")




class SearchForm(forms.Form):
    citta = forms.CharField(widget=forms.TextInput(
        attrs={'class':"form-control", 'placeholder':"Citta", 'id':"citySearch", 'name':"city"}))
    postiletto = forms.CharField(widget=forms.NumberInput(
        attrs={'class': "form-control", 'placeholder': "Numero Persone", 'id': "nPersSearch", 'name': "size"}))
    checkin = forms.CharField(widget=forms.DateInput(
        attrs={'type': 'date', 'class': "form-control", 'placeholder': "Dal", 'id': "fromSearch", 'name': "checkin"}))
    checkout = forms.CharField(widget=forms.DateInput(
        attrs={'type': 'date', 'class': "form-control", 'placeholder': "Al", 'id': "toSearch", 'name': "checkout"}))


class AddCameraForm(forms.Form):
    numero = forms.IntegerField(widget=forms.NumberInput(attrs = {'type':"Number", 'class':"form-control", 'id':"Numero", 'placeholder':"Numero", 'name':"numero"}))
    posti_letto = forms.IntegerField(widget=forms.NumberInput(attrs = {'type':"Text", 'class':"form-control", 'id':"Posti", 'placeholder':"Posti", 'name':"posti"}))
    servizi = forms.CharField(widget=forms.TextInput(attrs={'type':"Text",'class':"form-control",'id':"Servizi",'name':"servizi",'placeholder':"Wifi, Tv, Climatizzatore, Minifrigo"}))

    class Meta:
        model = Camera
        fields = ("numero", "posti_letto", "servizi")

    def save(self, hotel):
        camera = Camera.objects.create(hotel=hotel, numero=self.cleaned_data['numero'], posti_letto=self.cleaned_data['posti_letto'], servizi=self.cleaned_data['servizi'])
        camera.save()
        return camera

class LoginUserForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': "form-control", 'id':"exampleInputEmail1", 'aria-describedby':"emailHelp", 'placeholder':"Inserisci Email", 'name':"email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control", 'id':"exampleInputPassword1", 'placeholder':"Password", 'name':"password"}))

booking/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader

from .forms import RegisterUserForm, AddCameraForm, LoginUserForm, AddHotelForm, SearchForm
from .models import Camera, Prenotazione, Hotel
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .forms import *
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
import json.encoder

# Create your views here.



#pagina principale dove l'utente non collegato può prenotare la stanza
def index(request):

    if (request.method == "POST"):
        form = SearchForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data['citta']
            size = form.cleaned_data['postiletto']
            checkin = form.cleaned_data['checkin']
            checkout = form.cleaned_data['checkout']
            listaDisponibili = []
            for camera in Camera.objects.all():
                flag = False
                check = False
                if camera.posti_letto < int(float(size)) or camera.hotel.citta != city:
                    continue
                else:
                    for pren in Prenotazione.objects.all():
                        if pren.camera == camera:
                            new_checkin = datetime.strptime(checkin, "%Y-%m-%d")
                            new_checkout = datetime.strptime(checkout, "%Y-%m-%d")
                            pren_checkin = datetime.strptime(str(pren.checkin), "%Y-%m-%d")
                            pren_checkout = datetime.strptime(str(pren.checkout), "%Y-%m-%d")
                            if (pren_checkin <= new_checkin <= pren_checkout) or (
                                    pren_checkin <= new_checkout <= pren_checkout):
                                check = True
                            if new_checkin > new_checkout:
                                flag = True
                                break
                    if check is False:
                        listaDisponibili.append(camera)
                if flag == True:
                    break

            form = SearchForm()
            if (flag == True):
                context = {'dateError': True, 'form': form}
            elif (len(listaDisponibili) == 0):
                context = {'notAvailable': True, 'form': form}
            else:
                servizi = []
                for camera in listaDisponibili:
                    servizi.append(camera.servizi.split(", "))
                context = {'listaCamere': listaDisponibili, 'listaServizi': servizi, 'checkin': checkin,
                           'checkout': checkout, 'form': form}
        else:
            print("Form non valido - Search")
            context = {'searchFormError': True, 'form': form}
    else:
        form = SearchForm()
        context = {'form': form}
    return render(request, 'booking/index.html', context)

# #pagina di login
# def login(request):
#     return render(request, 'booking/login.html', {})

def registrazione(request):
    if (request.method == "POST"):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            newUser = form.save()
            albId = newUser .pk
            context = {'albid': albId}
            auth_login(request, newUser )
            #return render(request, 'booking/home.html', context)
            return redirect('/home/', context)
        else:
            print("Form non valido - Registrazione")
    else:
        form = RegisterUserForm()
        return render(request, 'booking/Registrazione.html', {'form': form})

def login(request):
    if request.method == "POST":
        form = LoginUserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('booking:home')
            else:
                context = {'loginerrato': True, 'form': form}
                return render(request, 'booking/login.html', context)
        else:
            context = {'formError': True, 'form': form}
            print("Form non valido - Registrazione")
            return render(request, 'booking/Registrazione.html', context)
    else:
        form = LoginUserForm()
        return render(request, 'booking/login.html', {'form': form})



def registrazione(request):
    return render(request, 'booking/Registrazione.html', {})

#submit del form di login, riporta alla home se login corretto o a loginerror se erratos
def hoteldetail(request):
    return render(request, 'booking/hoteldetail.html', {})


#riporta alla pagina di login mostrando un messaggio di errore
def loginError(request, loginErrato):
    context = {'loginerrato': loginErrato}
    return render(request, 'booking/login.html', context)

def search(request):
    city = request.POST.get("city", "")
    size = request.POST.get("size", "")
    checkin = request.POST.get("checkin", "")
    checkout = request.POST.get("checkout", "")
    listaDisponibili = []
    for camera in Camera.objects.all():
        flag = False
        check = False
        if camera.posti_letto < int(float(size)) or camera.hotel.citta != city:
            continue
        else:
            for pren in Prenotazione.objects.all():
                if pren.camera == camera:
                    new_checkin = datetime.strptime(checkin, "%Y-%m-%d")
                    new_checkout = datetime.strptime(checkout, "%Y-%m-%d")
                    pren_checkin = datetime.strptime(str(pren.checkin), "%Y-%m-%d")
                    pren_checkout = datetime.strptime(str(pren.checkout), "%Y-%m-%d")
                    if (pren_checkin <= new_checkin <= pren_checkout) or (pren_checkin <= new_checkout <= pren_checkout):
                        check = True
                    if new_checkin > new_checkout:
                        flag = True
                        break
            if check is False:
                listaDisponibili.append(camera)
        if flag==True:
            break

    if (flag == True):
        context = {'dateError': True}
    elif (len(listaDisponibili) == 0):
        context = {'notAvailable': True}
    else:
        servizi = []
        for camera in listaDisponibili:
            servizi.append(camera.servizi.split(", "))
        context = {'listaCamere': listaDisponibili, 'listaServizi': servizi, 'checkin': checkin,
                   'checkout': checkout}
    return render(request, 'booking/index.html', context)

#submit dell'email per la prenotazione, non avviene il refresh della pagina
def prenota(request):
    checkin = request.GET.get("checkin", "")
    checkout = request.GET.get("checkout", "")
    hotel = request.GET.get("hotel", "")
    camera = request.GET.get("camera", "")
    email = request.GET.get("email", "")
    hotelobj = Hotel.objects.get(nome=hotel)
    cameraobj = Camera.objects.get(hotel = hotelobj, numero=camera)
    newp = Prenotazione(email=email, camera=cameraobj, checkin=checkin, checkout=checkout)
    newp.save()
    return render(request, 'booking/index.html', {})

def manageCamera(request, hotel):
    if (request.method == "POST"):
        form = AddCameraForm(request.POST)
        if form.is_valid():

            posti_c = form.cleaned_data['posti_letto']
            numero_c = form.cleaned_data['numero']
            servizi_c = form.cleaned_data['servizi']

            all_servizi = ["Wifi", "Climatizzatore", "Tv", "Minifrigo"]
            check = False

            hotelObj = Hotel.objects.get(nome=hotel)
            citta = hotelObj.citta
            servizio = servizi_c.split(", ")

            alreadyexist = False
            checklength = Camera.objects.filter(hotel=hotelObj, numero=numero_c)
            if len(checklength) != 0:
                alreadyexist = True

            for serv in servizio:
                if (serv not in all_servizi or (len(servizio) != len(set(servizio)))):
                    check = True
                    break

            if not alreadyexist and not check:
                new_Camera = Camera.objects.create(hotel=hotelObj, numero=numero_c, posti_letto=posti_c, servizi=servizi_c)
                new_Camera.save()

            listaCamere = []
            for camera in Camera.objects.all():
                if camera.hotel == hotelObj:
                    listaCamere.append(camera)
            servizi = []
            for camera in listaCamere:
                servizi.append(camera.servizi.split(", "))

            form = AddCameraForm()

            if alreadyexist:
                context = {"hotel": hotel, "descrizione": hotelObj.descrizione, "indirizzo": hotelObj.indirizzo,
                           "listaCamere": listaCamere, "listaServizi": servizi, 'errorcamera': True, "citta": citta, 'form': form}
            elif check:
                context = {"hotel": hotel, "descrizione": hotelObj.descrizione, "indirizzo": hotelObj.indirizzo,
                           "listaCamere": listaCamere, "listaServizi": servizi, "erroreservizio": check, "citta": citta, 'form': form}
            else:
                context = {"hotel": hotel, "descrizione": hotelObj.descrizione, "indirizzo": hotelObj.indirizzo,
                           "listaCamere": listaCamere, "listaServizi": servizi, "citta": citta, 'form': form}

            return render(request, 'booking/hoteldetail.html', context)
        else:

booking/templates/booking/home.html
{% load staticfiles %}
{% load booking_extras %}
<html>

<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link href="{% static 'booking/style.css' %}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<title>Home</title>

</head>

<body>


<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'booking:home' %}">Booking</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'booking:home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'booking:hotels' %}">Lista Hotel</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'booking:logout' %}">
      <button class="btn btn-danger my-2 my-sm-0" type="submit">Logout</button>
    </form>
  </div>
</nav>

<!-- Fine Navbar -->


<div class="container tablehome">

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>

              <th scope="col">Hotel</th>
              <th scope="col">Camera</th>
              <th scope="col">Utente</th>
            </tr>
          </thead>
          <tbody>

            {% for i in length %}
            {% with index=forloop.counter0 %}
            {% with hotel=listaHotel|return_item:index %}
            {% with camera=listaCamere|return_item:index %}
            {% with user=listaUser|return_item:index %}

                <tr>
                    <td>{{hotel}}</td>
                    <td>{{camera}}</td>
                    <td>{{user}}</td>

                </tr>
            {% endwith %}
            {% endwith %}
            {% endwith %}
            {% endwith %}
            {% endfor %}

        </tbody>
    </table>

</div>

</body>

</html>

booking/templates/booking/index.html
{% load staticfiles %}
{% load booking_extras %}
<html>

<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link href="{% static 'booking/style.css' %}" rel="stylesheet" type="text/css">

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<title>Index</title>


</head>

<body>


<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Booking</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'booking:login' %}">Login<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'booking:registrazione'%}">Registrazione</a>
      </li>
    </ul>

  </div>
</nav>

<!-- Fine Navbar -->

<div class="container">
  <h3 class="h3-search">Prenota una camera</h3>
</div>

<div class="container searchform">
  <form id="searchrooms" method="post">
    {% csrf_token %}
    <div class="row container">
      <div class="col form-inline">
        <label class="labelSearch" for="{{form.citta.id_for_label}}">Città</label>
        <!--<input class="form-control" type="text" placeholder="Citta" id="citySearch" name="city" required/>-->
        {{form.citta}}
      </div>
      <div class="col form-inline">
        <label class="labelSearch" for="{{form.postiletto.id_for_label}}">Numero Persone</label>
        <!--<input class="form-control" type="number" placeholder="Numero Persone" id="nPersSearch" name="size" required/>-->
        {{form.postiletto}}
      </div>
      <div class="col form-inline">
        <label class="labelSearch" for="{{form.checkin.id_for_label}}">Da</label>
        <!--<input class="form-control" type="date" placeholder="Dal" id="fromSearch" name="checkin" required/>-->
        {{form.checkin}}
      </div>
      <div class="col form-inline">
        <label class="labelSearch" for="{{form.checkout.id_for_label}}">A</label>
        <!--<input class="form-control" type="date" placeholder="Al" id="toSearch" name="checkout" required/>-->
        {{form.checkout}}
      </div>
      <div class="col form-inline submitSearch">
        <button type="submit" class="btn btn-primary">Cerca</button>
      </div>
    </div>
  </form>
</div>


<div class="container h1-search">
  <h1>Risultati</h1>
</div>

{% if listaCamere %}
<div class="container tablesearch">
  <table class="table table-hover">
      <thead class="thead-dark">
          <tr>
            <th scope="col">Hotel</th>
            <th scope="col">Posti</th>
            <th scope="col">Servizi</th>
          </tr>
        </thead>
        <tbody id="searchBody">
        {% for camera in listaCamere %}
        {% with index=forloop.counter0 %}
        {% with servizio=listaServizi|return_item:index %}
          <tr>
            <td data-camera="{{camera.numero}}">{{camera.hotel.nome}}</td>
            <td>{{camera.posti_letto}}</td>
            <td>
              {% for serv in servizio %}
              {{serv}}<br />
              {% endfor %}
            </td>
          </tr>
        {% endwith %}
        {% endwith %}
        {% endfor %}
      </tbody>
  </table>
  <div class="container popupprenota" id="popupprenota">
    <h4>Inserisci la mail e conferma la tua prenotazione.</h4>
        <form id="formPrenota">
            <div class="row container">
              <div class="col form-inline mailcontainer">
                <input class="form-control" type="email" id="mailPrenota" placeholder = "Inserisci la tua mail" name="email">
              </div>
              <div class="col form-inline btnprenota">
                <button type="submit" class="btn btn-primary" id="prenotaBtn">Prenota</button>
                <button type="button" class="btn btn-danger" id="annullaPrenota">Annulla</button>
              </div>
             </div>
        </form>
    <p class="text-success" id="prenEff">Prenotazione effettuata</p>
  </div>
</div>
{% endif %}

{% if notAvailable %}
<div class="container searchnoresult">
  <h3>Nessun risultato trovato</h3>
</div>
{% endif %}
{% if dateError %}
  <div class="container searchnoresult">
    <h3>Hai inserito una data errata</h3>
  </div>
  {% endif %}

  {% if dateError %}
  <div class="container searchnoresult">
    <h3>Hai inserito una data errata</h3>
  </div>
  {% endif %}


<script>

  var popup = document.getElementById("popupprenota");
  var tableRows = document.getElementById("searchBody").getElementsByTagName("tr");
  var pEff = document.getElementById("prenEff");
  var annullaPrenota = document.getElementById("annullaPrenota");
  var prenotaBtn = document.getElementById("prenotaBtn");


  /*Dati ottenuti dopo il click sulla riga*/

  var hotel;
  var camera;

  for (i = 0; i < tableRows.length; i++)
    {

      // console.log(row);
      tableRows[i].onclick = function()
      {
        popup.style.visibility = "visible";
        popup.style.opacity = 1;
        pEff.style.visibility = "hidden";

        /*Devo prendere i dati della camera: hotel e camera*/

        camera = this.getElementsByTagName("td")[0].getAttribute("data-camera");
        hotel = this.getElementsByTagName("td")[0].textContent;

        console.log(camera);
        console.log(hotel);
        console.log("{{checkin}}");
        console.log("{{checkout}}");

      };
    }

    annullaPrenota.onclick = function()
    {
      popup.style.visibility = "hidden";
      popup.style.opacity = 0;
    };

    // prenotaBtn.onclick = function()
    // {
    //   pEff.style.visibility = "visible";
    // };

    $("#formPrenota").on("submit", function(e)
    {
        e.preventDefault();
        pEff.style.visibility = "visible";

        console.log($("#mailPrenota").val());

        $.ajax(
          {
            type: "get",
            url: "{% url 'booking:prenota' %}",
            data:
            {
                "hotel": hotel,
                "camera": camera.toString(),
                "email": $("#mailPrenota").val(),
                "checkin": "{{checkin}}",
                "checkout": "{{checkout}}"
            },
              success: function (data)
              {
                  console.log("success");
                  console.log("data");
              },
              failure: function (data)
              {
                  console.log("failure");
                  console.log("data");
              }
          });
    });

</script>

</body>

</html>